site_name: Bpod Wiki
# copyright: Copyright &copy; 2023 Sanworks LLC  # is this accurate?
repo_url: https://github.com/sanworks/Bpod_Gen2  # the top right's repo link
repo_name: Sanworks/Bpod_Gen2
edit_uri: https://github.com/sanworks/Bpod_Wiki/tree/main/docs/  # where the features content.action.edit and content.action.view link to

nav:
  - Home: index.md
  - Hardware:
      - assembly/index.md
      - State Machines:
        - assembly/state-machine-assembly-0_5.md
        - assembly/state-machine-assembly-0_9-1_0.md
        - assembly/state-machine-assembly-2_3-2_4.md
        - assembly/state-machine-assembly-2_5.md
        - assembly/state-machine-assembly-2+.md
      - Gen2 Modules:
        - assembly/analog-input-module-assembly.md
        - assembly/analog-output-module-assembly.md
        - assembly/hifi-module-assembly.md
        - assembly/rotary-encoder-module-assembly.md
        - assembly/valve-driver-module-assembly.md
        - assembly/port-array-module-assembly.md
        - assembly/dds-module-assembly.md
        - assembly/ethernet-module-assembly.md
        - assembly/snes-module-assembly.md
        - assembly/arduino-shield-gen2-assembly.md
        - assembly/teensy-shield-assembly.md
        - assembly/raspberry-pi-shim-assembly.md
      - Gen1 Modules:
        - assembly/arduino-shield-0-5-assembly.md
        - assembly/open-ephys-module-assembly.md
        - assembly/neuralynx-sync-board-assembly.md
      - Behavior Ports:
        - assembly/lickometer-assembly.md
        - assembly/mouse-behavior-port-assembly.md
        - assembly/port-breakout-board-assembly.md
        - assembly/mouse-box-assembly.md
      - Bench Testing:
        - user-guide/bench-testing-bpod.md
  - Firmware:
    - install-and-update/firmware-repo-list.md
    - install-and-update/firmware-update.md
  - MATLAB Software:
    - user-guide/index.md
    - Setup:
      - install-and-update/installing-bpod.md
      - install-and-update/software-update.md
    - Operation:
      - user-guide/state-machine-concept.md
      - user-guide/bpod-gui.md
    - Programming:
      - user-guide/protocol-development.md
      - Function Reference: # IMPORTANT NOTE: New functions are not automatically added to the function-reference/index.md page!
                            # Please add them manually, using the file's convention.
        - function-reference/index.md
        - function-reference/initialization.md
        - function-reference/bpodsystem-fields.md
        - function-reference/bpodsystem-functions.md
        - function-reference/state-machine-creation.md
        - function-reference/running-statemachine.md
        - function-reference/running-protocol.md
        - function-reference/data-storage.md
        - function-reference/general-plugins.md
        - function-reference/serial-message-setup.md
        - function-reference/module-matlab-usb.md
        - function-reference/module-matlab-fsm.md
        - function-reference/pc-fsm-softcodes.md
        - function-reference/liquid-calibration.md
      - Bpod Module APIs:
        - module-documentation/index.md
        - module-documentation/analog-input-module.md
        - Analog Output Module:
          - module-documentation/waveplayer.md
          - module-documentation/audioplayer.md
          - module-documentation/pulsepal-module.md
        - module-documentation/hifi-module.md
        - module-documentation/rotary-encoder-module.md
        - module-documentation/valve-driver-module.md
        - module-documentation/smart-servo-module.md
        - module-documentation/dds-module.md
        - module-documentation/I2C-messenger-module.md
      - Example Code:
        - user-guide/example-code.md

    - Integrations:
      - user-guide/using-bonsai.md
      - user-guide/using-bcontrol.md
  - Serial Interfaces:
    - serial-interfaces/fsm-serial-interface-v18.md
    - serial-interfaces/analogue-input-module-serial-interface.md
    - serial-interfaces/waveplayer-serial-interface.md
    - serial-interfaces/audioplayer-serial-interface.md
    - serial-interfaces/hifi-module-serial-interface.md
    - serial-interfaces/rotary-encoder-module-serial-interface.md
    - serial-interfaces/valve-module-serial-interface.md
    - serial-interfaces/port-array-module-serial-interface.md
    - serial-interfaces/smartservo-module-serial-interface.md
    - serial-interfaces/blink-module-serial-interface.md
  - Companion Devices:
    - companion-devices/pulsepal.md
    - companion-devices/frame2ttl.md
  - Project Info:
    - project-info/legal.md
    - project-info/code-of-conduct.md
    - project-info/contact.md
# nav:
#   - Home: index.md
#   - User Guide:
#     - user-guide/index.md
#     - Additional guides:
#       - user-guide/bpod-gui.md
#       - user-guide/protocol-development.md
#       - user-guide/visual-stimulus-integration.md
#       - user-guide/using-bcontrol.md
#   - Functions:
#     - function-reference/index.md
#     - Function Reference:

#   - Modules:
#     - module-documentation/index.md
#     - Plugins:

#     - Serial Interfaces:

#   - Assembly:
#     - assembly/index.md

#   - External links:
#     - "Sanworks": "https://sanworks.io"
#     - "Forums": "https://sanworks.io/forums"
#     - "GitHub": "https://github.com/sanworks/Bpod_Gen2"
#

not_in_nav: |
  /module-documentation/readme.md
  /serial-interfaces/fsm-serial-interface-v17.md
  /function-reference/updating-bpod.md


markdown_extensions:
  - admonition  # callouts/alerts
  - attr_list
  - md_in_html
  - markdown.extensions.extra
  - footnotes
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - search

theme:
  name: material
  features:
    - navigation.sections # use titles rather than expanding items
    # - navigation.expand # expand all items
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
  # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  logo: https://avatars.githubusercontent.com/u/17090284?v=4
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github

# todo: ask Josh for google analytics code
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX

extra_css:
  - https://fonts.googleapis.com/css2?family=Aldrich
  - extra.css
